# [package]
# name = "demo"
# version = "0.0.0"

# [dependencies]
# MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }
# MoveNursery= { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib/nursery", rev = "main" }

# [addresses]
# std =  "0x1"

[package]
name = "BasicCoin"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }

[addresses]
std =  "0x1"
NamedAddr = "0xCAFE"
